### ISSUE TITLE
Possibility to add all results to a list and navigate through them?

### ISSUE THREAD

**Issue by ShengYun** [ameyp/CscopeSublime#22]
Hi,

first of all thank you very much for this nice plugin.

Is it possible to add all the results into the history list and navigate through the list via ctrl+shift+[ ?

the current implementation won't clear the list when querying new symbols, and I can't afford manually hitting enter on every result.

btw, is it possible to update cscope_out automatically?

**Comment by vanrijn** [comment]
Okay, so the first idea I'm not going to try to implement. I'm open to reviewing patches and pull requests if someone else wants to implement this in a clean way. But I prefer the way this plugin currently works (a single results buffer). As for the second idea, it was a great idea and I included this functionality in a recent commit. So this can be closed now. Thanks for the ideas! =:)
