### ISSUE TITLE
Add an option to create/refresh Cscope database

### ISSUE THREAD

**Issue by gatopeich** [ameyp/CscopeSublime#39]
Would be more handy if we could refresh Cscope's DB from within Sublime.

**Comment by vanrijn** [comment]
Yeah, I agree. Sorry for the ridiculously long delay in answering. =:(

This has been bugging me a long time too and I'm just looking at how to fix this. One problem I see is that I don't think there's necessarily a standard way of doing this in cscope proper, is there? I've been using a horrible little shell script named cscope-indexer for more than a decade to do this on my Linux/OS X systems. Looks like there's a copy here: http://opensource.apple.com//source/cscope/cscope-13/cscope/contrib/xcscope/cscope-indexer . But that's not going to work on Windows machines, etc.

Maybe if I add a configurable "CscopeSublime_database_rebuild_command" setting or something? Do you have any thoughts on how to do this cleanly?

**Comment by vanrijn** [comment]
So I merged a solution to provide this functionality. I'm definitely open to more suggestions and comments. Please give it a shot when you get a chance and let me know what you think. Thanks!!

**Comment by gatopeich** [comment]
Thanks, I will check it out...
