### ISSUE TITLE
in search window can not go to definition if the file in not opened in sublime.

### ISSUE THREAD

**Issue by huaihuaiVV** [ameyp/CscopeSublime#55]
i like this plugin,
but i found in search result window,
if the file that contains the search symbol have not been opened in sublime,
the GoTo definition menu is invisible.
can not jump to the file .

how to let it can open and jump to this file automatically ?

Thanks a lot~

**Comment by huaihuaiVV** [comment]
<img width="1440" alt="wx20170124-102051 2x" src="https://cloud.githubusercontent.com/assets/5601971/22231481/d92c21f4-e21e-11e6-970e-4608247f3b41.png">

**Comment by huaihuaiVV** [comment]
<img width="1440" alt="wx20170124-102153 2x" src="https://cloud.githubusercontent.com/assets/5601971/22231501/f48c4762-e21e-11e6-90cf-b54ab7ac2229.png">

**Comment by vanrijn** [comment]
Hi there. You have to click on the line you want to go to and press your "enter" or "return" key on your keyboard. Sublime Text 3 still doesn't have the concept of contexts for mouse events, so this is the best we can do for now.

**Comment by wanyaoqi** [comment]
> Hi there. You have to click on the line you want to go to and press your "enter" or "return" key on your keyboard. **Sublime Text 3 still doesn't have the concept of contexts for mouse events**, so this is the best we can do for now.

Hi @vanrijn, is not same with  `ctrl + f` search ?  In the case of `ctrl + f`, I can enter the file by click the mouse.

**Comment by vanrijn** [comment]
Hi wanyaoqi, correct, it is not the same. ST3 handles this differently than plugins are able to.
