### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DimaWittmann** [ameyp/CscopeSublime#58]
Hi, every one,
I got this error on Sublime Text 3, 

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/home/wittmann/.config/sublime-text-3/Packages/CscopeSublime/cscope.py", line 467, in run
    self.database.update_location(self.view.file_name())
  File "/home/wittmann/.config/sublime-text-3/Packages/CscopeSublime/cscope.py", line 60, in update_location
    project_info_paths = [folder['path'] for folder in project_info['folders']]
TypeError: 'NoneType' object is not subscriptable

Thank you,
Dmytrii

**Comment by vanrijn** [comment]
Hey @DimaWittmann, thanks so much for the bug report. Could you please attach or paste the project file that you're using when you hit this error? I'm not sure how you're able to hit this error in particular. =:) Thanks!

**Comment by vanrijn** [comment]
I just pushed a change up to see if it might fix this, @DimaWittmann. Can you please let me know if this fixes the problem for you? Also, please do let me see the project file you're working with that triggered this error so I can make sure the problem is fully fixed. Thank you again! =:)

**Comment by DimaWittmann** [comment]
Thank you, it helps.
I did not create project file in sublime, is it get created automatically when I just open files?

I also has another problems that when I call cscope, close cscope tab and rerun cscope, sublime opens two tabs. And so on as I open more tabs and close them.

**Comment by vanrijn** [comment]
Okay so it sounds like you don't see this crash anymore and that's a good thing. =:) @DimaWittmann can you please open a new issue for the multiple tab issue that you're seeing so I can look into it? Thanks!!

**Comment by DimaWittmann** [comment]
Okay, 
Thank you!)
