### ISSUE TITLE
All the previous Cscope results files open for every new lookup

### ISSUE THREAD

**Issue by rvlad-patrascu** [ameyp/CscopeSublime#59]
Hi,

Whenever I look up something, a new Cscope results output file is opened along with all the other files from previous searches.

Thanks

**Comment by cynkiller** [comment]
I also met with this problem.. The cscope result windows would be too much after several usage..

**Comment by guestoo** [comment]
yes, it's really annoying.

**Comment by vanrijn** [comment]
Hi guys. Sorry this is happening. I will try to look at this one today or tomorrow. Could one of you guys give me simple steps to reproduce what you guys are seeing so I can find and fix this quicker?

**Comment by guestoo** [comment]
Here is my reproduce steps:
1. Look up symbol AAA, then Cscope results_AAA is popup.
2. Look up symbol BBB, then Cscope results_BBB is popup.
3. Close results_AAA and results_BBB.
4. Look up symbol CCC. Not only results_CCC is popup but also results_AAA and results_BBB.

I always meet this on Sublime Text 3 build 3126.

**Comment by vanrijn** [comment]
So sorry about this guys. That was an oversight on my part. This should be fixed now. Thanks for letting me know!!
