### ISSUE TITLE
how to create cscope.out

### ISSUE THREAD

**Issue by abramhum** [ameyp/CscopeSublime#65]
Hi:
I use sublime text3 and try to create cscope.out, but I don't know how, 
my environment is Windows 10, and I have download cscope.exe
Thanks

**Comment by vanrijn** [comment]
You need to configure your user settings for this plugin and set the cscope executable location properly. Then make sure you're working with a ST3 project that has 1 path defined. Then you can use the rebuild database plugin command to generate the cscope database.

**Comment by abramhum** [comment]
I found the answer, it's simple, just use cmd, and the use the command 
`cscope.exe -b -q -k  filename`
after that, the system will create  cscope.out, and work well under ST3
