### ISSUE TITLE
How to change the hot key in sublime text3?

### ISSUE THREAD

**Issue by bgylde** [ameyp/CscopeSublime#66]
It's a very cool tool, thanks for sharing it.

**Comment by LazyRen** [comment]
Use Package Resource Viewer to extract & open cscope package.
open your Default(OS).sublime-keymap

change what ever you like.

**Comment by vanrijn** [comment]
Er, yeah thanks for answering, @LazyRen. The main page of this github repo explains how to customize the hot key.

**Comment by pqrth** [comment]
Thanks @vanrijn, this plugin is really helpful.

Forgive me for being naive, but I couldn't figure out a way to update a keyboard binding following [README.md#configuration](https://github.com/ameyp/CscopeSublime#configuration) and I don't want to use _Package Resource Viewer_ every time the plugin updates. Could you please help me update a key binding?
