### ISSUE TITLE
cscope error on ST3  " 'ascii' codec can't decode byte 0xe1 " with OSX10.12 

### ISSUE THREAD

**Issue by LazyRen** [ameyp/CscopeSublime#68]
I once had CscopeSublimeSearchWorker has no attribute "output" so I used Package Resource Viewer to add self.output = "" for Worker class.
It now does not provide any error for such, but I still get only empty file opened when I type commands for cscope.

And here is the new(or existed but ignored because of above error) error that I get when I launch cscope.

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/LazyRen/Library/Application Support/Sublime Text 3/Packages/Cscope/cscope.py", line 397, in run
    matches = self.run_cscope(self.mode, self.symbol)
  File "/Users/LazyRen/Library/Application Support/Sublime Text 3/Packages/Cscope/cscope.py", line 377, in run_cscope
    output, erroroutput = proc.communicate()
  File "./python3.3/subprocess.py", line 920, in communicate
  File "./python3.3/subprocess.py", line 1577, in _communicate
  File "./python3.3/subprocess.py", line 848, in _translate_newlines
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 67: ordinal not in range(128)

**Comment by vanrijn** [comment]
Ah good catch on the output attribute, thank you!

I wonder what is in your cscope database, or at least what is returned by the lookup. Can you please run this command from a terminal prompt (replace "XXX" with a symbol in your project) and paste the output in a comment?

# cscope -dL -f `pwd`/cscope.out -0XXX

Thank you!

**Comment by LazyRen** [comment]
at first it returned "cannot read trailer offset from file cscope.out". It was due to spaces on pwd. so I've changed all spaces within path. Now it returns

cscope -dL -f cscope.out -0exec
defs.h panic 26 int exec(char *, char **);
exec.c exec 11 exec(char *path, char **argv)
init.c main 30 exec("sh", argv);
sh.c runcmd 78 exec(ecmd->argv[0], ecmd->argv);
sysfile.c sys_exec 420 return exec(path, argv);
user.h exit 13 int exec(char *, char **);
usertests.c exectest 297 if(exec("echo", echoargv) < 0){
usertests.c bigargtest 1626 exec("echo", args);
usys.S SYSCALL 19 SYSCALL(exec)

from the terminal.

while sublime cscope still returns nothing.

In folder /Users/LazyRen/Documents/Programming/TEST
Found 0 matches for C symbol: exec
--------------------------------------------------

In folder /Users/LazyRen/Google드라이브/3-1/운영체제/os2018/xv6-public
Found 0 matches for global definition: *
exec
--------------------------------------------------

**Comment by vanrijn** [comment]
Actually, I think it wasn't the spaces... I think you had non-ascii characters in your path? I think this might still be a problem....

**Comment by LazyRen** [comment]
Yes I had non-ascii char(korean).
But I still have those, and it works fine. Only thing I’ve changed is removing white space from the path.

**Comment by vanrijn** [comment]
That's weird. The original error was "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 67: ordinal not in range(128)". I thought that was coming from the non-ascii characters in your path. But you're saying you still have those in your path and now cscopesublime plugin works fine and finds results?

**Comment by LazyRen** [comment]
yes indeed

**Comment by LazyRen** [comment]
But after a bit search on the problem. I think it might be the problem of filename encoding.
I used this path for my google drive which is used by both windows and mac.
Windows use utf16 for the filename while mac uses utf8.
While removing white spaces from the file name maybe the encoding also got changed and I guess that might have solved the problem?

Thus cscope works fine with white spaces existing in filename usually?

**Comment by vanrijn** [comment]
So I've fixed the output attribute error. Thanks very much for reporting that, @LazyRen! I guess I'm not sure what to do with this issue at this point. Is there anything that is actionable now? What would you like me to do with this? =:)

**Comment by LazyRen** [comment]
I guess now it’s matter of cscope developer for the space issues...
Thank you for fast response and such a good package. For the encoding matter, I don’t see the ways to fix it.

**Comment by vanrijn** [comment]
Ok, well I'll mark this as closed for now. Thanks again for the help, @LazyRen. If you hit any more problems, please let me know and open a new issue for it! =:)
